### PR TITLE
solving coding bug

### PR DESCRIPTION
**Pull request by thealiev**

### CODE REVIEW

**Comment by thealiev** [comment]
solving ex1,2

**Review by thealiev — COMMENTED** [review]
..........

**Review by jkalandarov — COMMENTED** [review]
Good job!
I will close MR.

P.S: There were no instructions to change JSDOC.

**Comment by thealiev** [comment]
when will the answer be given?

**Comment by jkalandarov** [comment]
You will be notified by email after December 27th.

**Comment by thealiev** [comment]
Hi, Jasurbek Kalandarov
I hope this message finds you well. I wanted to follow up as I have not yet
received a response to my previous email sent via Gmail. Could you please
confirm if it was received?
Thank you for your attention to this matter. I look forward to your reply.

Best regards,
Salohiddin Tojiev

ср, 25 дек. 2024 г. в 21:42, Jasurbek Kalandarov ***@***.***>:

**Comment by jkalandarov** [comment]
Hi!
I've not received any email from you. If you've written to the recruiter or others, they will reply after holidays.

**Pull request closed without merging**
